services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: backend:latest
    env_file: ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - fluxion-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: frontend:latest
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    networks:
      - fluxion-network

networks:
  fluxion-network:
    driver: bridge