name: Build CLI and Create Release

on:
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Minimum required to checkout the code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Checks out the repository to load the source code

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: .go-version # Ensures consistent Go version

      - name: Install Dependencies
        run: go mod download
        # Ensures all Go dependencies are installed

      - name: Build the CLI
        run: go build -o app ./cmd
        # Builds the CLI application using the specified command

  release:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-cli-app
        path: ./app

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: go-cli-app/app
